### PR TITLE
Create quick_start.md Issues #25

### PR DESCRIPTION
**Pull request by BinniesLite**
**Issues**
https://github.com/codethesaurus/docs/issues/25

**Title**
Create quick_start.md

**Description**
Write a quick start page for developers to contribute to the project

### CODE REVIEW

**Comment by BinniesLite** [comment]
Let me know if you want to adjust anything

**Review by geekygirlsarah — APPROVED** [review]
Looks good! I might add a couple of things, but I like you had a couple of things I hadn't thought of too. Thank you!

And thank you for your first Code Thesaurus contribution! This counts towards [Hacktoberfest](https://hacktoberfest.com/) if you wanted to participate. Don't forget to register so this counts!

**Comment by geekygirlsarah** [comment]
(Also the errors seem to be on Netlify's side, not as a result of this file. I'll go fix that too!)

**Comment by BinniesLite** [comment]
Awesome, glad that I can help!

**Pull request merged**
